/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics;

/**
 *
 * @author steau_000
 */
public class ClientTeacherUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientTeacherUI
     */
    public ClientTeacherUI() {
        initComponents();
    }
    
    private int nbAnswer = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupAnswer = new javax.swing.JFrame();
        jPanelPopup1 = new javax.swing.JPanel();
        labelPopup = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaPopup = new javax.swing.JTextArea();
        buttonValidateAnswer = new javax.swing.JButton();
        buttonCancelAnswer = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelMain = new javax.swing.JPanel();
        comboBoxQuestionType = new javax.swing.JComboBox<>();
        labelAnswer = new javax.swing.JLabel();
        labelQuestionText = new javax.swing.JLabel();
        labelQuestionType = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaQuestionText = new javax.swing.JTextArea();
        buttonAddAnswer = new javax.swing.JButton();
        buttonDeleteAnswer1 = new javax.swing.JButton();
        labelCustomAnswer1 = new javax.swing.JLabel();
        labelCustomAnswer2 = new javax.swing.JLabel();
        buttonDeleteAnswer2 = new javax.swing.JButton();
        labelCustomAnswer3 = new javax.swing.JLabel();
        buttonDeleteAnswer3 = new javax.swing.JButton();
        buttonDeleteAnswer4 = new javax.swing.JButton();
        labelCustomAnswer4 = new javax.swing.JLabel();
        labelCustomAnswer5 = new javax.swing.JLabel();
        buttonDeleteAnswer5 = new javax.swing.JButton();
        buttonDeleteAnswer6 = new javax.swing.JButton();
        labelCustomAnswer6 = new javax.swing.JLabel();
        labelCustomAnswer7 = new javax.swing.JLabel();
        buttonDeleteAnswer7 = new javax.swing.JButton();
        labelCustomAnswer8 = new javax.swing.JLabel();
        buttonDeleteAnswer8 = new javax.swing.JButton();
        buttonBackMenu = new javax.swing.JButton();
        buttonValidateFinal = new javax.swing.JButton();
        jPanelWaitAnswer = new javax.swing.JPanel();

        popupAnswer.setTitle("Ajouter une réponse");
        popupAnswer.setResizable(false);
        popupAnswer.setSize(new java.awt.Dimension(520, 220));

        labelPopup.setText("Libellé de la réponse");

        textAreaPopup.setColumns(20);
        textAreaPopup.setRows(5);
        jScrollPane3.setViewportView(textAreaPopup);

        buttonValidateAnswer.setText("Valider");
        buttonValidateAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValidateAnswerActionPerformed(evt);
            }
        });

        buttonCancelAnswer.setText("Annuler");
        buttonCancelAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelAnswerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPopup1Layout = new javax.swing.GroupLayout(jPanelPopup1);
        jPanelPopup1.setLayout(jPanelPopup1Layout);
        jPanelPopup1Layout.setHorizontalGroup(
            jPanelPopup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPopup1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPopup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanelPopup1Layout.createSequentialGroup()
                        .addComponent(labelPopup)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelPopup1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(buttonValidateAnswer)
                .addGap(18, 18, 18)
                .addComponent(buttonCancelAnswer)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanelPopup1Layout.setVerticalGroup(
            jPanelPopup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPopup1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPopup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPopup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonValidateAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancelAnswer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout popupAnswerLayout = new javax.swing.GroupLayout(popupAnswer.getContentPane());
        popupAnswer.getContentPane().setLayout(popupAnswerLayout);
        popupAnswerLayout.setHorizontalGroup(
            popupAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(popupAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popupAnswerLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPopup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        popupAnswerLayout.setVerticalGroup(
            popupAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(popupAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popupAnswerLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPopup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setTitle("Client Teacher");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        comboBoxQuestionType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Choisir>", "Choix unique", "Choix multiple", "Ouverte" }));
        comboBoxQuestionType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxQuestionTypeActionPerformed(evt);
            }
        });

        labelAnswer.setText("Réponse(s)");

        labelQuestionText.setText("Libellé de la question");

        labelQuestionType.setText("Type de question");

        textAreaQuestionText.setColumns(20);
        textAreaQuestionText.setRows(3);
        jScrollPane1.setViewportView(textAreaQuestionText);

        buttonAddAnswer.setText("Ajouter une réponse");
        buttonAddAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddAnswerActionPerformed(evt);
            }
        });

        buttonDeleteAnswer1.setText("Supprimer");
        buttonDeleteAnswer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAnswer1ActionPerformed(evt);
            }
        });

        labelCustomAnswer1.setText("Reponse 1");

        labelCustomAnswer2.setText("Reponse 2");

        buttonDeleteAnswer2.setText("Supprimer");
        buttonDeleteAnswer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAnswer2ActionPerformed(evt);
            }
        });

        labelCustomAnswer3.setText("Reponse 3");

        buttonDeleteAnswer3.setText("Supprimer");
        buttonDeleteAnswer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAnswer3ActionPerformed(evt);
            }
        });

        buttonDeleteAnswer4.setText("Supprimer");
        buttonDeleteAnswer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAnswer4ActionPerformed(evt);
            }
        });

        labelCustomAnswer4.setText("Reponse 4");

        labelCustomAnswer5.setText("Reponse 5");

        buttonDeleteAnswer5.setText("Supprimer");
        buttonDeleteAnswer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAnswer5ActionPerformed(evt);
            }
        });

        buttonDeleteAnswer6.setText("Supprimer");
        buttonDeleteAnswer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAnswer6ActionPerformed(evt);
            }
        });

        labelCustomAnswer6.setText("Reponse 6");

        labelCustomAnswer7.setText("Reponse 7");

        buttonDeleteAnswer7.setText("Supprimer");
        buttonDeleteAnswer7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAnswer7ActionPerformed(evt);
            }
        });

        labelCustomAnswer8.setText("Reponse 8");

        buttonDeleteAnswer8.setText("Supprimer");
        buttonDeleteAnswer8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAnswer8ActionPerformed(evt);
            }
        });

        buttonBackMenu.setText("Retour menu");
        buttonBackMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackMenuActionPerformed(evt);
            }
        });

        buttonValidateFinal.setText("Valider");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelQuestionText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxQuestionType, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 34, Short.MAX_VALUE))))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCustomAnswer8, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCustomAnswer7, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCustomAnswer6, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCustomAnswer5, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCustomAnswer4, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCustomAnswer3, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCustomAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buttonAddAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelCustomAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonDeleteAnswer8)
                            .addComponent(buttonDeleteAnswer7)
                            .addComponent(buttonDeleteAnswer6)
                            .addComponent(buttonDeleteAnswer5)
                            .addComponent(buttonDeleteAnswer4)
                            .addComponent(buttonDeleteAnswer3)
                            .addComponent(buttonDeleteAnswer2)
                            .addComponent(buttonDeleteAnswer1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonValidateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(buttonBackMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
            .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelQuestionType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(comboBoxQuestionType, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(labelQuestionText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAddAnswer)
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteAnswer1)
                    .addComponent(labelCustomAnswer1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteAnswer2)
                    .addComponent(labelCustomAnswer2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteAnswer3)
                    .addComponent(labelCustomAnswer3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteAnswer4)
                    .addComponent(labelCustomAnswer4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteAnswer5)
                    .addComponent(labelCustomAnswer5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteAnswer6)
                    .addComponent(labelCustomAnswer6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteAnswer7)
                    .addComponent(labelCustomAnswer7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteAnswer8)
                    .addComponent(labelCustomAnswer8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBackMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonValidateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMainLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(labelQuestionType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(502, Short.MAX_VALUE)))
        );

        labelAnswer.setVisible(false);
        buttonAddAnswer.setVisible(false);
        buttonDeleteAnswer1.setVisible(false);
        labelCustomAnswer1.setVisible(false);
        labelCustomAnswer2.setVisible(false);
        buttonDeleteAnswer2.setVisible(false);
        labelCustomAnswer3.setVisible(false);
        buttonDeleteAnswer3.setVisible(false);
        buttonDeleteAnswer4.setVisible(false);
        labelCustomAnswer4.setVisible(false);
        labelCustomAnswer5.setVisible(false);
        buttonDeleteAnswer5.setVisible(false);
        buttonDeleteAnswer6.setVisible(false);
        labelCustomAnswer6.setVisible(false);
        labelCustomAnswer7.setVisible(false);
        buttonDeleteAnswer7.setVisible(false);
        labelCustomAnswer8.setVisible(false);
        buttonDeleteAnswer8.setVisible(false);

        jTabbedPane2.addTab("Question", jPanelMain);

        javax.swing.GroupLayout jPanelWaitAnswerLayout = new javax.swing.GroupLayout(jPanelWaitAnswer);
        jPanelWaitAnswer.setLayout(jPanelWaitAnswerLayout);
        jPanelWaitAnswerLayout.setHorizontalGroup(
            jPanelWaitAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        jPanelWaitAnswerLayout.setVerticalGroup(
            jPanelWaitAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Réponses", jPanelWaitAnswer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxQuestionTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxQuestionTypeActionPerformed
        
        String index = (String)comboBoxQuestionType.getSelectedItem();
        
        if (index.equals("<Choisir>") || index.equals("Ouverte")){
            labelAnswer.setVisible(false);
            buttonAddAnswer.setVisible(false);
        }else{
            labelAnswer.setVisible(true);
            buttonAddAnswer.setVisible(true);
        }
        
    }//GEN-LAST:event_comboBoxQuestionTypeActionPerformed

    private void buttonAddAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddAnswerActionPerformed
        
        popupAnswer.setLocation(600, 300);
        popupAnswer.setVisible(true);
        

    }//GEN-LAST:event_buttonAddAnswerActionPerformed

    private void buttonValidateAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValidateAnswerActionPerformed
        
        
        
        switch(nbAnswer){
            case 0:
                labelCustomAnswer1.setVisible(true);
                labelCustomAnswer1.setText(textAreaPopup.getText());
                buttonDeleteAnswer1.setVisible(true);
                break;
            case 1:
                labelCustomAnswer2.setVisible(true);
                labelCustomAnswer2.setText(textAreaPopup.getText());
                buttonDeleteAnswer2.setVisible(true);
                buttonDeleteAnswer1.setVisible(false);
                break;
            case 2:
                labelCustomAnswer3.setVisible(true);
                labelCustomAnswer3.setText(textAreaPopup.getText());
                buttonDeleteAnswer3.setVisible(true);
                buttonDeleteAnswer2.setVisible(false);
                break;
            case 3:
                labelCustomAnswer4.setVisible(true);
                labelCustomAnswer4.setText(textAreaPopup.getText());
                buttonDeleteAnswer4.setVisible(true);
                buttonDeleteAnswer3.setVisible(false);
                break;
            case 4:
                labelCustomAnswer5.setVisible(true);
                labelCustomAnswer5.setText(textAreaPopup.getText());
                buttonDeleteAnswer5.setVisible(true);
                buttonDeleteAnswer4.setVisible(false);
                break;
            case 5:
                labelCustomAnswer6.setVisible(true);
                labelCustomAnswer6.setText(textAreaPopup.getText());
                buttonDeleteAnswer6.setVisible(true);
                buttonDeleteAnswer5.setVisible(false);
                break;
            case 6:
                labelCustomAnswer7.setVisible(true);
                labelCustomAnswer7.setText(textAreaPopup.getText());
                buttonDeleteAnswer7.setVisible(true);
                buttonDeleteAnswer6.setVisible(false);
                break;
            case 7:
                labelCustomAnswer8.setVisible(true);
                labelCustomAnswer8.setText(textAreaPopup.getText());
                buttonDeleteAnswer8.setVisible(true);
                buttonDeleteAnswer7.setVisible(false);
                break;
            default:
                break;
        }
        
        textAreaPopup.setText("");
        nbAnswer +=1;
        popupAnswer.setVisible(false);
        
    }//GEN-LAST:event_buttonValidateAnswerActionPerformed

    private void buttonCancelAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelAnswerActionPerformed
        popupAnswer.setVisible(false);
    }//GEN-LAST:event_buttonCancelAnswerActionPerformed

    private void buttonDeleteAnswer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAnswer1ActionPerformed
        labelCustomAnswer1.setVisible(false);
        buttonDeleteAnswer1.setVisible(false);
        nbAnswer-=1;
    }//GEN-LAST:event_buttonDeleteAnswer1ActionPerformed

    private void buttonDeleteAnswer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAnswer2ActionPerformed
        labelCustomAnswer2.setVisible(false);
        buttonDeleteAnswer2.setVisible(false);
        buttonDeleteAnswer1.setVisible(true);
        nbAnswer-=1;
    }//GEN-LAST:event_buttonDeleteAnswer2ActionPerformed

    private void buttonDeleteAnswer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAnswer3ActionPerformed
        labelCustomAnswer3.setVisible(false);
        buttonDeleteAnswer3.setVisible(false);
        buttonDeleteAnswer2.setVisible(true);
        nbAnswer-=1;
    }//GEN-LAST:event_buttonDeleteAnswer3ActionPerformed

    private void buttonDeleteAnswer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAnswer4ActionPerformed
        labelCustomAnswer4.setVisible(false);
        buttonDeleteAnswer4.setVisible(false);
        buttonDeleteAnswer3.setVisible(true);
        nbAnswer-=1;
    }//GEN-LAST:event_buttonDeleteAnswer4ActionPerformed

    private void buttonDeleteAnswer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAnswer5ActionPerformed
        labelCustomAnswer5.setVisible(false);
        buttonDeleteAnswer5.setVisible(false);
        buttonDeleteAnswer4.setVisible(true);
        nbAnswer-=1;
    }//GEN-LAST:event_buttonDeleteAnswer5ActionPerformed

    private void buttonDeleteAnswer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAnswer6ActionPerformed
        labelCustomAnswer6.setVisible(false);
        buttonDeleteAnswer6.setVisible(false);
        buttonDeleteAnswer5.setVisible(true);
        nbAnswer-=1;
    }//GEN-LAST:event_buttonDeleteAnswer6ActionPerformed

    private void buttonDeleteAnswer7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAnswer7ActionPerformed
        labelCustomAnswer7.setVisible(false);
        buttonDeleteAnswer7.setVisible(false);
        buttonDeleteAnswer6.setVisible(true);
        nbAnswer-=1;
    }//GEN-LAST:event_buttonDeleteAnswer7ActionPerformed

    private void buttonDeleteAnswer8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAnswer8ActionPerformed
        labelCustomAnswer8.setVisible(false);
        buttonDeleteAnswer8.setVisible(false);
        buttonDeleteAnswer7.setVisible(true);
        nbAnswer-=1;
    }//GEN-LAST:event_buttonDeleteAnswer8ActionPerformed

    private void buttonBackMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackMenuActionPerformed
        //Window.setVisible(false);
    }//GEN-LAST:event_buttonBackMenuActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    
    private void startManagement(){
        
        labelCustomAnswer1.setVisible(false);
        labelCustomAnswer2.setVisible(false);
        labelCustomAnswer3.setVisible(false);
        labelCustomAnswer4.setVisible(false);
        labelCustomAnswer5.setVisible(false);
        labelCustomAnswer6.setVisible(false);
        labelCustomAnswer7.setVisible(false);
        labelCustomAnswer8.setVisible(false);
        
        buttonDeleteAnswer1.setVisible(false);
        buttonDeleteAnswer2.setVisible(false);
        buttonDeleteAnswer3.setVisible(false);
        buttonDeleteAnswer4.setVisible(false);
        buttonDeleteAnswer5.setVisible(false);
        buttonDeleteAnswer6.setVisible(false);
        buttonDeleteAnswer7.setVisible(false);
        buttonDeleteAnswer8.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientTeacherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientTeacherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientTeacherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientTeacherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientTeacherUI().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddAnswer;
    private javax.swing.JButton buttonBackMenu;
    private javax.swing.JButton buttonCancelAnswer;
    private javax.swing.JButton buttonDeleteAnswer1;
    private javax.swing.JButton buttonDeleteAnswer2;
    private javax.swing.JButton buttonDeleteAnswer3;
    private javax.swing.JButton buttonDeleteAnswer4;
    private javax.swing.JButton buttonDeleteAnswer5;
    private javax.swing.JButton buttonDeleteAnswer6;
    private javax.swing.JButton buttonDeleteAnswer7;
    private javax.swing.JButton buttonDeleteAnswer8;
    private javax.swing.JButton buttonValidateAnswer;
    private javax.swing.JButton buttonValidateFinal;
    private javax.swing.JComboBox<String> comboBoxQuestionType;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelPopup1;
    private javax.swing.JPanel jPanelWaitAnswer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel labelAnswer;
    private javax.swing.JLabel labelCustomAnswer1;
    private javax.swing.JLabel labelCustomAnswer2;
    private javax.swing.JLabel labelCustomAnswer3;
    private javax.swing.JLabel labelCustomAnswer4;
    private javax.swing.JLabel labelCustomAnswer5;
    private javax.swing.JLabel labelCustomAnswer6;
    private javax.swing.JLabel labelCustomAnswer7;
    private javax.swing.JLabel labelCustomAnswer8;
    private javax.swing.JLabel labelPopup;
    private javax.swing.JLabel labelQuestionText;
    private javax.swing.JLabel labelQuestionType;
    private javax.swing.JFrame popupAnswer;
    private javax.swing.JTextArea textAreaPopup;
    private javax.swing.JTextArea textAreaQuestionText;
    // End of variables declaration//GEN-END:variables
}
