/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics;

import client.IOCommandes;
import client.IOCommandesTeacher;
import client.Questionnaire;

/**
 *
 * @author steau_000
 */
public class ClientTeacherUI extends javax.swing.JFrame {
	private Questionnaire question;
	private IOCommandesTeacher teacher;

    /**
     * Creates new form ClientTeacherUI
     */
    public ClientTeacherUI() {
        initComponents();
    }

    public ClientTeacherUI(String username, IOCommandesTeacher teacher) {
        initComponents();
        this.question = new Questionnaire(username);
        this.teacher = teacher;
    }

    private int nbAnswer = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupAnswer = new javax.swing.JFrame();
        jPanelPopup1 = new javax.swing.JPanel();
        labelPopup = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaPopup = new javax.swing.JTextArea();
        buttonValidateAnswer = new javax.swing.JButton();
        buttonCancelAnswer = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelMain = new javax.swing.JPanel();
        jPanelQuestionType = new javax.swing.JPanel();
        comboBoxQuestionType = new javax.swing.JComboBox<>();
        jPanelQuestionText = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaQuestionText = new javax.swing.JTextArea();
        jPanelAnswersChoice = new javax.swing.JPanel();
        buttonAddAnswer = new javax.swing.JButton();
        buttonDeleteAnswer1 = new javax.swing.JButton();
        labelCustomAnswer1 = new javax.swing.JLabel();
        labelCustomAnswer2 = new javax.swing.JLabel();
        buttonDeleteAnswer2 = new javax.swing.JButton();
        labelCustomAnswer3 = new javax.swing.JLabel();
        buttonDeleteAnswer3 = new javax.swing.JButton();
        buttonDeleteAnswer4 = new javax.swing.JButton();
        labelCustomAnswer4 = new javax.swing.JLabel();
        labelCustomAnswer5 = new javax.swing.JLabel();
        buttonDeleteAnswer5 = new javax.swing.JButton();
        buttonDeleteAnswer6 = new javax.swing.JButton();
        labelCustomAnswer6 = new javax.swing.JLabel();
        labelCustomAnswer7 = new javax.swing.JLabel();
        buttonDeleteAnswer7 = new javax.swing.JButton();
        labelCustomAnswer8 = new javax.swing.JLabel();
        buttonDeleteAnswer8 = new javax.swing.JButton();
        buttonValidateFinal = new javax.swing.JButton();
        jPanelWaitAnswer = new javax.swing.JPanel();
        jPanelQuestion = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textPaneQuestion = new javax.swing.JTextPane();
        jPanelUserList = new javax.swing.JPanel();
        jPanelAnswers = new javax.swing.JPanel();
        jPanelOnAir = new javax.swing.JPanel();
        buttonNewQuestion = new javax.swing.JButton();

        popupAnswer.setTitle("Ajouter une réponse");
        popupAnswer.setResizable(false);
        popupAnswer.setSize(new java.awt.Dimension(520, 220));

        labelPopup.setText("Libellé de la réponse");

        textAreaPopup.setColumns(20);
        textAreaPopup.setRows(5);
        jScrollPane3.setViewportView(textAreaPopup);

        buttonValidateAnswer.setText("Valider");
        buttonValidateAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValidateAnswerActionPerformed(evt);
            }
        });

        buttonCancelAnswer.setText("Annuler");
        buttonCancelAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelAnswerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPopup1Layout = new javax.swing.GroupLayout(jPanelPopup1);
        jPanelPopup1.setLayout(jPanelPopup1Layout);
        jPanelPopup1Layout.setHorizontalGroup(
            jPanelPopup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPopup1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPopup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanelPopup1Layout.createSequentialGroup()
                        .addComponent(labelPopup)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelPopup1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(buttonValidateAnswer)
                .addGap(18, 18, 18)
                .addComponent(buttonCancelAnswer)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanelPopup1Layout.setVerticalGroup(
            jPanelPopup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPopup1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPopup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPopup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonValidateAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancelAnswer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout popupAnswerLayout = new javax.swing.GroupLayout(popupAnswer.getContentPane());
        popupAnswer.getContentPane().setLayout(popupAnswerLayout);
        popupAnswerLayout.setHorizontalGroup(
            popupAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(popupAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popupAnswerLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPopup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        popupAnswerLayout.setVerticalGroup(
            popupAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(popupAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popupAnswerLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPopup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client Teacher");
        setLocation(new java.awt.Point(400, 150));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanelQuestionType.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type de question", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        comboBoxQuestionType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Choisir>", "Choix unique", "Choix multiple", "Ouverte" }));
        comboBoxQuestionType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxQuestionTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelQuestionTypeLayout = new javax.swing.GroupLayout(jPanelQuestionType);
        jPanelQuestionType.setLayout(jPanelQuestionTypeLayout);
        jPanelQuestionTypeLayout.setHorizontalGroup(
            jPanelQuestionTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuestionTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboBoxQuestionType, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelQuestionTypeLayout.setVerticalGroup(
            jPanelQuestionTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuestionTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboBoxQuestionType, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelQuestionText.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Libellé de la question", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        textAreaQuestionText.setColumns(20);
        textAreaQuestionText.setRows(3);
        jScrollPane1.setViewportView(textAreaQuestionText);

        javax.swing.GroupLayout jPanelQuestionTextLayout = new javax.swing.GroupLayout(jPanelQuestionText);
        jPanelQuestionText.setLayout(jPanelQuestionTextLayout);
        jPanelQuestionTextLayout.setHorizontalGroup(
            jPanelQuestionTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelQuestionTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelQuestionTextLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelQuestionTextLayout.setVerticalGroup(
            jPanelQuestionTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
            .addGroup(jPanelQuestionTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelQuestionTextLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        jPanelAnswersChoice.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Réponses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        buttonAddAnswer.setText("Ajouter une réponse");
        buttonAddAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddAnswerActionPerformed(evt);
            }
        });

        buttonDeleteAnswer1.setText("Supprimer");
        buttonDeleteAnswer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAnswer1ActionPerformed(evt);
            }
        });

        labelCustomAnswer1.setText("Reponse 1");

        labelCustomAnswer2.setText("Reponse 2");

        buttonDeleteAnswer2.setText("Supprimer");
        buttonDeleteAnswer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAnswer2ActionPerformed(evt);
            }
        });

        labelCustomAnswer3.setText("Reponse 3");

        buttonDeleteAnswer3.setText("Supprimer");
        buttonDeleteAnswer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAnswer3ActionPerformed(evt);
            }
        });

        buttonDeleteAnswer4.setText("Supprimer");
        buttonDeleteAnswer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAnswer4ActionPerformed(evt);
            }
        });

        labelCustomAnswer4.setText("Reponse 4");

        labelCustomAnswer5.setText("Reponse 5");

        buttonDeleteAnswer5.setText("Supprimer");
        buttonDeleteAnswer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAnswer5ActionPerformed(evt);
            }
        });

        buttonDeleteAnswer6.setText("Supprimer");
        buttonDeleteAnswer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAnswer6ActionPerformed(evt);
            }
        });

        labelCustomAnswer6.setText("Reponse 6");

        labelCustomAnswer7.setText("Reponse 7");

        buttonDeleteAnswer7.setText("Supprimer");
        buttonDeleteAnswer7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAnswer7ActionPerformed(evt);
            }
        });

        labelCustomAnswer8.setText("Reponse 8");

        buttonDeleteAnswer8.setText("Supprimer");
        buttonDeleteAnswer8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAnswer8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAnswersChoiceLayout = new javax.swing.GroupLayout(jPanelAnswersChoice);
        jPanelAnswersChoice.setLayout(jPanelAnswersChoiceLayout);
        jPanelAnswersChoiceLayout.setHorizontalGroup(
            jPanelAnswersChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnswersChoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAnswersChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCustomAnswer8, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCustomAnswer7, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCustomAnswer6, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCustomAnswer5, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCustomAnswer4, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCustomAnswer3, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCustomAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAnswersChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(buttonAddAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCustomAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanelAnswersChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonDeleteAnswer8)
                    .addComponent(buttonDeleteAnswer7)
                    .addComponent(buttonDeleteAnswer6)
                    .addComponent(buttonDeleteAnswer5)
                    .addComponent(buttonDeleteAnswer4)
                    .addComponent(buttonDeleteAnswer3)
                    .addComponent(buttonDeleteAnswer2)
                    .addComponent(buttonDeleteAnswer1))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanelAnswersChoiceLayout.setVerticalGroup(
            jPanelAnswersChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnswersChoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonAddAnswer)
                .addGap(18, 18, 18)
                .addGroup(jPanelAnswersChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteAnswer1)
                    .addComponent(labelCustomAnswer1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAnswersChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteAnswer2)
                    .addComponent(labelCustomAnswer2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAnswersChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteAnswer3)
                    .addComponent(labelCustomAnswer3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAnswersChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteAnswer4)
                    .addComponent(labelCustomAnswer4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAnswersChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteAnswer5)
                    .addComponent(labelCustomAnswer5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAnswersChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteAnswer6)
                    .addComponent(labelCustomAnswer6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAnswersChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteAnswer7)
                    .addComponent(labelCustomAnswer7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAnswersChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteAnswer8)
                    .addComponent(labelCustomAnswer8))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        buttonAddAnswer.setVisible(false);
        buttonDeleteAnswer1.setVisible(false);
        labelCustomAnswer1.setVisible(false);
        labelCustomAnswer2.setVisible(false);
        buttonDeleteAnswer2.setVisible(false);
        labelCustomAnswer3.setVisible(false);
        buttonDeleteAnswer3.setVisible(false);
        buttonDeleteAnswer4.setVisible(false);
        labelCustomAnswer4.setVisible(false);
        labelCustomAnswer5.setVisible(false);
        buttonDeleteAnswer5.setVisible(false);
        buttonDeleteAnswer6.setVisible(false);
        labelCustomAnswer6.setVisible(false);
        labelCustomAnswer7.setVisible(false);
        buttonDeleteAnswer7.setVisible(false);
        labelCustomAnswer8.setVisible(false);
        buttonDeleteAnswer8.setVisible(false);

        buttonValidateFinal.setText("Valider");
        buttonValidateFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValidateFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonValidateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(348, 348, 348))
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelQuestionType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelQuestionText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAnswersChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanelQuestionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelQuestionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAnswersChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonValidateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Question", jPanelMain);

        jPanelQuestion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Question", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        textPaneQuestion.setEditable(false);
        jScrollPane2.setViewportView(textPaneQuestion);

        javax.swing.GroupLayout jPanelQuestionLayout = new javax.swing.GroupLayout(jPanelQuestion);
        jPanelQuestion.setLayout(jPanelQuestionLayout);
        jPanelQuestionLayout.setHorizontalGroup(
            jPanelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanelQuestionLayout.setVerticalGroup(
            jPanelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuestionLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelUserList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Users list", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        javax.swing.GroupLayout jPanelUserListLayout = new javax.swing.GroupLayout(jPanelUserList);
        jPanelUserList.setLayout(jPanelUserListLayout);
        jPanelUserListLayout.setHorizontalGroup(
            jPanelUserListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );
        jPanelUserListLayout.setVerticalGroup(
            jPanelUserListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        jPanelAnswers.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Répartition des réponses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        javax.swing.GroupLayout jPanelAnswersLayout = new javax.swing.GroupLayout(jPanelAnswers);
        jPanelAnswers.setLayout(jPanelAnswersLayout);
        jPanelAnswersLayout.setHorizontalGroup(
            jPanelAnswersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );
        jPanelAnswersLayout.setVerticalGroup(
            jPanelAnswersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        jPanelOnAir.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dernière réponse", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        javax.swing.GroupLayout jPanelOnAirLayout = new javax.swing.GroupLayout(jPanelOnAir);
        jPanelOnAir.setLayout(jPanelOnAirLayout);
        jPanelOnAirLayout.setHorizontalGroup(
            jPanelOnAirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        jPanelOnAirLayout.setVerticalGroup(
            jPanelOnAirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        buttonNewQuestion.setText("Poser une nouvelle question");
        buttonNewQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewQuestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelWaitAnswerLayout = new javax.swing.GroupLayout(jPanelWaitAnswer);
        jPanelWaitAnswer.setLayout(jPanelWaitAnswerLayout);
        jPanelWaitAnswerLayout.setHorizontalGroup(
            jPanelWaitAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWaitAnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWaitAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOnAir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelWaitAnswerLayout.createSequentialGroup()
                        .addGroup(jPanelWaitAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelAnswers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanelUserList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWaitAnswerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonNewQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelWaitAnswerLayout.setVerticalGroup(
            jPanelWaitAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWaitAnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWaitAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelUserList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelWaitAnswerLayout.createSequentialGroup()
                        .addComponent(jPanelQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelAnswers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelOnAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonNewQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Réponses", jPanelWaitAnswer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxQuestionTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxQuestionTypeActionPerformed

        String index = (String)comboBoxQuestionType.getSelectedItem();
        System.out.println(comboBoxQuestionType.getSelectedItem());
        if (index.equals("<Choisir>") || index.equals("Ouverte")){
            buttonAddAnswer.setVisible(false);
            
            labelCustomAnswer1.setVisible(false);
            labelCustomAnswer2.setVisible(false);
            labelCustomAnswer3.setVisible(false);
            labelCustomAnswer4.setVisible(false);
            labelCustomAnswer5.setVisible(false);
            labelCustomAnswer6.setVisible(false);
            labelCustomAnswer7.setVisible(false);
            labelCustomAnswer8.setVisible(false);
            buttonDeleteAnswer1.setVisible(false);
            buttonDeleteAnswer2.setVisible(false);
            buttonDeleteAnswer3.setVisible(false);
            buttonDeleteAnswer4.setVisible(false);
            buttonDeleteAnswer5.setVisible(false);
            buttonDeleteAnswer6.setVisible(false);
            buttonDeleteAnswer7.setVisible(false);
            buttonDeleteAnswer8.setVisible(false);
            
            this.question.clearAnswers();
            
        }else{
            buttonAddAnswer.setVisible(true);
        }

        switch(index) {
        	case "Choix unique" :
        		this.question.setQuestionType("UNIQUE");
        		break;
        	case "Choix multiple" :
        		this.question.setQuestionType("MULTIPLE");
        		break;
        	case "Ouverte" :
        		this.question.setQuestionType("OPEN");
        		break;
        }

	

    }//GEN-LAST:event_comboBoxQuestionTypeActionPerformed

    private void buttonAddAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddAnswerActionPerformed

        popupAnswer.setLocation(600, 300);
        popupAnswer.setVisible(true);


    }//GEN-LAST:event_buttonAddAnswerActionPerformed

    private void buttonValidateAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValidateAnswerActionPerformed

    	this.question.addAnswer(textAreaPopup.getText());

        switch(nbAnswer){
            case 0:
                labelCustomAnswer1.setVisible(true);
                labelCustomAnswer1.setText(textAreaPopup.getText());
                buttonDeleteAnswer1.setVisible(true);
                break;
            case 1:
                labelCustomAnswer2.setVisible(true);
                labelCustomAnswer2.setText(textAreaPopup.getText());
                buttonDeleteAnswer2.setVisible(true);
                buttonDeleteAnswer1.setVisible(false);
                break;
            case 2:
                labelCustomAnswer3.setVisible(true);
                labelCustomAnswer3.setText(textAreaPopup.getText());
                buttonDeleteAnswer3.setVisible(true);
                buttonDeleteAnswer2.setVisible(false);
                break;
            case 3:
                labelCustomAnswer4.setVisible(true);
                labelCustomAnswer4.setText(textAreaPopup.getText());
                buttonDeleteAnswer4.setVisible(true);
                buttonDeleteAnswer3.setVisible(false);
                break;
            case 4:
                labelCustomAnswer5.setVisible(true);
                labelCustomAnswer5.setText(textAreaPopup.getText());
                buttonDeleteAnswer5.setVisible(true);
                buttonDeleteAnswer4.setVisible(false);
                break;
            case 5:
                labelCustomAnswer6.setVisible(true);
                labelCustomAnswer6.setText(textAreaPopup.getText());
                buttonDeleteAnswer6.setVisible(true);
                buttonDeleteAnswer5.setVisible(false);
                break;
            case 6:
                labelCustomAnswer7.setVisible(true);
                labelCustomAnswer7.setText(textAreaPopup.getText());
                buttonDeleteAnswer7.setVisible(true);
                buttonDeleteAnswer6.setVisible(false);
                break;
            case 7:
                labelCustomAnswer8.setVisible(true);
                labelCustomAnswer8.setText(textAreaPopup.getText());
                buttonDeleteAnswer8.setVisible(true);
                buttonDeleteAnswer7.setVisible(false);
                break;
            default:
                break;
        }

        textAreaPopup.setText("");
        nbAnswer +=1;
        popupAnswer.setVisible(false);

    }//GEN-LAST:event_buttonValidateAnswerActionPerformed

    private void buttonCancelAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelAnswerActionPerformed
        popupAnswer.setVisible(false);
    }//GEN-LAST:event_buttonCancelAnswerActionPerformed

    private void buttonDeleteAnswer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAnswer1ActionPerformed
    	this.question.removeAnswer(labelCustomAnswer1.getText());
    	labelCustomAnswer1.setVisible(false);
        buttonDeleteAnswer1.setVisible(false);
        nbAnswer-=1;
    }//GEN-LAST:event_buttonDeleteAnswer1ActionPerformed

    private void buttonDeleteAnswer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAnswer2ActionPerformed
    	this.question.removeAnswer(labelCustomAnswer2.getText());
    	labelCustomAnswer2.setVisible(false);
        buttonDeleteAnswer2.setVisible(false);
        buttonDeleteAnswer1.setVisible(true);
        nbAnswer-=1;
    }//GEN-LAST:event_buttonDeleteAnswer2ActionPerformed

    private void buttonDeleteAnswer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAnswer3ActionPerformed
    	this.question.removeAnswer(labelCustomAnswer3.getText());
    	labelCustomAnswer3.setVisible(false);
        buttonDeleteAnswer3.setVisible(false);
        buttonDeleteAnswer2.setVisible(true);
        nbAnswer-=1;
    }//GEN-LAST:event_buttonDeleteAnswer3ActionPerformed

    private void buttonDeleteAnswer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAnswer4ActionPerformed
    	this.question.removeAnswer(labelCustomAnswer4.getText());
    	labelCustomAnswer4.setVisible(false);
        buttonDeleteAnswer4.setVisible(false);
        buttonDeleteAnswer3.setVisible(true);
        nbAnswer-=1;
    }//GEN-LAST:event_buttonDeleteAnswer4ActionPerformed

    private void buttonDeleteAnswer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAnswer5ActionPerformed
    	this.question.removeAnswer(labelCustomAnswer5.getText());
    	labelCustomAnswer5.setVisible(false);
        buttonDeleteAnswer5.setVisible(false);
        buttonDeleteAnswer4.setVisible(true);
        nbAnswer-=1;
    }//GEN-LAST:event_buttonDeleteAnswer5ActionPerformed

    private void buttonDeleteAnswer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAnswer6ActionPerformed
    	this.question.removeAnswer(labelCustomAnswer6.getText());
    	labelCustomAnswer6.setVisible(false);
        buttonDeleteAnswer6.setVisible(false);
        buttonDeleteAnswer5.setVisible(true);
        nbAnswer-=1;
    }//GEN-LAST:event_buttonDeleteAnswer6ActionPerformed

    private void buttonDeleteAnswer7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAnswer7ActionPerformed
    	this.question.removeAnswer(labelCustomAnswer7.getText());
    	labelCustomAnswer7.setVisible(false);
        buttonDeleteAnswer7.setVisible(false);
        buttonDeleteAnswer6.setVisible(true);
        nbAnswer-=1;
    }//GEN-LAST:event_buttonDeleteAnswer7ActionPerformed

    private void buttonDeleteAnswer8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAnswer8ActionPerformed
    	this.question.removeAnswer(labelCustomAnswer8.getText());
    	labelCustomAnswer8.setVisible(false);
        buttonDeleteAnswer8.setVisible(false);
        buttonDeleteAnswer7.setVisible(true);
        nbAnswer-=1;
    }//GEN-LAST:event_buttonDeleteAnswer8ActionPerformed



    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    	this.teacher.ecrireReseau("quit");
    	this.teacher.ecrireEcran("BYE BYE");
    	this.teacher.interrupt();
    }//GEN-LAST:event_formWindowClosed

    private void buttonValidateFinalActionPerformed(java.awt.event.ActionEvent evt) {
    	System.out.println("VALIDATE");
    	IOCommandes monIOCommandes = new IOCommandes();

    	this.question.setLabel(textAreaQuestionText.getText());
    	System.out.println((String) this.question.getQuestions());
    	this.teacher.ecrireReseau((String) this.question.getQuestions());
        
         textPaneQuestion.setText(textAreaQuestionText.getText());
         jTabbedPane.setSelectedIndex(1);

    }

		private void buttonNewQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewQuestionActionPerformed
                    jTabbedPane.setSelectedIndex(0);
                    comboBoxQuestionType.setSelectedIndex(0);
                    this.question.clearAnswers();
                    
                    buttonAddAnswer.setVisible(false);
            
                    labelCustomAnswer1.setVisible(false);
                    labelCustomAnswer2.setVisible(false);
                    labelCustomAnswer3.setVisible(false);
                    labelCustomAnswer4.setVisible(false);
                    labelCustomAnswer5.setVisible(false);
                    labelCustomAnswer6.setVisible(false);
                    labelCustomAnswer7.setVisible(false);
                    labelCustomAnswer8.setVisible(false);
                    buttonDeleteAnswer1.setVisible(false);
                    buttonDeleteAnswer2.setVisible(false);
                    buttonDeleteAnswer3.setVisible(false);
                    buttonDeleteAnswer4.setVisible(false);
                    buttonDeleteAnswer5.setVisible(false);
                    buttonDeleteAnswer6.setVisible(false);
                    buttonDeleteAnswer7.setVisible(false);
                    buttonDeleteAnswer8.setVisible(false);
                    
                    textAreaQuestionText.setText("");

    }//GEN-LAST:event_buttonNewQuestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientTeacherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientTeacherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientTeacherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientTeacherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientTeacherUI().setVisible(true);


            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddAnswer;
    private javax.swing.JButton buttonCancelAnswer;
    private javax.swing.JButton buttonDeleteAnswer1;
    private javax.swing.JButton buttonDeleteAnswer2;
    private javax.swing.JButton buttonDeleteAnswer3;
    private javax.swing.JButton buttonDeleteAnswer4;
    private javax.swing.JButton buttonDeleteAnswer5;
    private javax.swing.JButton buttonDeleteAnswer6;
    private javax.swing.JButton buttonDeleteAnswer7;
    private javax.swing.JButton buttonDeleteAnswer8;
    private javax.swing.JButton buttonNewQuestion;
    private javax.swing.JButton buttonValidateAnswer;
    private javax.swing.JButton buttonValidateFinal;
    private javax.swing.JComboBox<String> comboBoxQuestionType;
    private javax.swing.JPanel jPanelAnswers;
    private javax.swing.JPanel jPanelAnswersChoice;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelOnAir;
    private javax.swing.JPanel jPanelPopup1;
    private javax.swing.JPanel jPanelQuestion;
    private javax.swing.JPanel jPanelQuestionText;
    private javax.swing.JPanel jPanelQuestionType;
    private javax.swing.JPanel jPanelUserList;
    private javax.swing.JPanel jPanelWaitAnswer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel labelCustomAnswer1;
    private javax.swing.JLabel labelCustomAnswer2;
    private javax.swing.JLabel labelCustomAnswer3;
    private javax.swing.JLabel labelCustomAnswer4;
    private javax.swing.JLabel labelCustomAnswer5;
    private javax.swing.JLabel labelCustomAnswer6;
    private javax.swing.JLabel labelCustomAnswer7;
    private javax.swing.JLabel labelCustomAnswer8;
    private javax.swing.JLabel labelPopup;
    private javax.swing.JFrame popupAnswer;
    private javax.swing.JTextArea textAreaPopup;
    private javax.swing.JTextArea textAreaQuestionText;
    private javax.swing.JTextPane textPaneQuestion;
    // End of variables declaration//GEN-END:variables
}
